UPDATE channel SET xmltvid='30644', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC ONE Lon';
UPDATE channel SET xmltvid='17154', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC TWO';
UPDATE channel SET xmltvid='17468', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV';
UPDATE channel SET xmltvid='17155', useonairguide=0, commmethod=-1 WHERE callsign = 'Channel 4';
UPDATE channel SET xmltvid='17157', useonairguide=0, commmethod=-1 WHERE callsign = 'Channel 5';
UPDATE channel SET xmltvid='20630', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV2';
UPDATE channel SET xmltvid='84926', useonairguide=0, commmethod=-1 WHERE callsign = 'London Live';
UPDATE channel SET xmltvid='20684', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC FOUR';
UPDATE channel SET xmltvid='44643', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV3';
UPDATE channel SET xmltvid='48021', useonairguide=0, commmethod=-1 WHERE callsign = 'Pick';
UPDATE channel SET xmltvid='24305', useonairguide=0, commmethod=-1 WHERE callsign = 'Dave';
UPDATE channel SET xmltvid='56892', useonairguide=0, commmethod=-1 WHERE callsign = 'Channel 4+1';
UPDATE channel SET xmltvid='47657', useonairguide=0, commmethod=-1 WHERE callsign = 'More 4';
UPDATE channel SET xmltvid='21494', useonairguide=0, commmethod=-1 WHERE callsign = 'Film4';
UPDATE channel SET xmltvid='45828', useonairguide=0, commmethod=-1 WHERE callsign = 'Really';
UPDATE channel SET xmltvid='31783', useonairguide=0, commmethod=-1 WHERE callsign = 'Yesterday';
UPDATE channel SET xmltvid='82575', useonairguide=0, commmethod=-1 WHERE callsign = 'Drama';
UPDATE channel SET xmltvid='52335', useonairguide=0, commmethod=-1 WHERE callsign = '5 USA';
UPDATE channel SET xmltvid='48020', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV4';
UPDATE channel SET xmltvid='21257', useonairguide=0, commmethod=-1 WHERE callsign = 'Home';
UPDATE channel SET xmltvid='90855', useonairguide=0, commmethod=-1 WHERE callsign = 'ITVBe';
UPDATE channel SET xmltvid='53059', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV2 +1';
UPDATE channel SET xmltvid='25117', useonairguide=0, commmethod=-1 WHERE callsign = 'E4';
UPDATE channel SET xmltvid='33882', useonairguide=0, commmethod=-1 WHERE callsign = 'E4+1';
UPDATE channel SET xmltvid='52336', useonairguide=0, commmethod=-1 WHERE callsign = '5STAR';
UPDATE channel SET xmltvid='97330', useonairguide=0, commmethod=-1 WHERE callsign = 'Spike';
UPDATE channel SET xmltvid='88796', useonairguide=0, commmethod=-1 WHERE callsign = 'Movie Mix';
UPDATE channel SET xmltvid='65160', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV +1';
UPDATE channel SET xmltvid='98366', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV3+1';
UPDATE channel SET xmltvid='62391', useonairguide=0, commmethod=-1 WHERE callsign = 'QUEST';
UPDATE channel SET xmltvid='65394', useonairguide=0, commmethod=-1 WHERE callsign = 'QUEST+1';
UPDATE channel SET xmltvid='44718', useonairguide=0, commmethod=-1 WHERE callsign = 'Food Network';
UPDATE channel SET xmltvid='77749', useonairguide=0, commmethod=-1 WHERE callsign = 'Channel 5+1';
UPDATE channel SET xmltvid='21793', useonairguide=0, commmethod=-1 WHERE callsign = 'Challenge';
UPDATE channel SET xmltvid='75804', useonairguide=0, commmethod=-1 WHERE callsign = '4seven';
UPDATE channel SET xmltvid='46306', useonairguide=0, commmethod=-1 WHERE callsign = 'movies4men';
UPDATE channel SET xmltvid='99098', useonairguide=0, commmethod=-1 WHERE callsign = 'True Crime';
UPDATE channel SET xmltvid='57747', useonairguide=0, commmethod=-1 WHERE callsign = 'True Entertainment';
UPDATE channel SET xmltvid='73970', useonairguide=0, commmethod=-1 WHERE callsign = 'CBS Action';
UPDATE channel SET xmltvid='97332', useonairguide=0, commmethod=-1 WHERE callsign = 'TBN UK';
UPDATE channel SET xmltvid='31756', useonairguide=0, commmethod=-1 WHERE callsign = 'CBS Reality';
UPDATE channel SET xmltvid='97331', useonairguide=0, commmethod=-1 WHERE callsign = 'truTV';
UPDATE channel SET xmltvid='97674', useonairguide=0, commmethod=-1 WHERE callsign = 'YourTV';
UPDATE channel SET xmltvid='44855', useonairguide=0, commmethod=-1 WHERE callsign = 'Dave ja vu';
UPDATE channel SET xmltvid='29324', useonairguide=0, commmethod=-2 WHERE callsign = 'CBBC';
UPDATE channel SET xmltvid='29325', useonairguide=0, commmethod=-2 WHERE callsign = 'CBeebies';
UPDATE channel SET xmltvid='49452', useonairguide=0, commmethod=-1 WHERE callsign = 'CITV';
UPDATE channel SET xmltvid='33638', useonairguide=0, commmethod=-1 WHERE callsign = 'POP';
UPDATE channel SET xmltvid='34087', useonairguide=0, commmethod=-1 WHERE callsign = 'Tiny Pop';
UPDATE channel SET xmltvid='19037', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC NEWS';
UPDATE channel SET xmltvid='20685', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC Parliament';
UPDATE channel SET xmltvid='16234', useonairguide=0, commmethod=-1 WHERE callsign = 'Sky News';
