UPDATE channel SET xmltvid='london.bbc1.bbc.co.uk', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC ONE Lon';
UPDATE channel SET xmltvid='england.bbc2.bbc.co.uk', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC TWO';
UPDATE channel SET xmltvid='london.itv1.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV';
UPDATE channel SET xmltvid='channel4.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Channel 4';
UPDATE channel SET xmltvid='channel5.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Channel 5';
UPDATE channel SET xmltvid='itv2.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV2';
UPDATE channel SET xmltvid='bbcthree.bbc.co.uk', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC THREE';
UPDATE channel SET xmltvid='londonlive.standard.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'London Live';
UPDATE channel SET xmltvid='bbcfour.bbc.co.uk', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC FOUR';
UPDATE channel SET xmltvid='itv3.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV3';
UPDATE channel SET xmltvid='pick.sky.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Pick';
UPDATE channel SET xmltvid='dave.uktv.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'Dave';
UPDATE channel SET xmltvid='plus-1.channel4.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Channel 4+1';
UPDATE channel SET xmltvid='more4.channel4.com', useonairguide=0, commmethod=-1 WHERE callsign = 'More 4';
UPDATE channel SET xmltvid='filmfour.channel4.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Film4';
UPDATE channel SET xmltvid='really.uktv.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'Really';
UPDATE channel SET xmltvid='yesterday.uktv.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'Yesterday';
UPDATE channel SET xmltvid='drama.uktv.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'Drama';
UPDATE channel SET xmltvid='fiveusa.channel5.com', useonairguide=0, commmethod=-1 WHERE callsign = '5 USA';
UPDATE channel SET xmltvid='itv4.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV4';
UPDATE channel SET xmltvid='plus-1.dave.uktv.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'Dave ja vu';
UPDATE channel SET xmltvid='be.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'ITVBe';
UPDATE channel SET xmltvid='plus-1.itv2.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV2 +1';
UPDATE channel SET xmltvid='e4.channel4.com', useonairguide=0, commmethod=-1 WHERE callsign = 'E4';
UPDATE channel SET xmltvid='plus-1.e4.channel4.com', useonairguide=0, commmethod=-1 WHERE callsign = 'E4+1';
UPDATE channel SET xmltvid='fivestar.channel5.com', useonairguide=0, commmethod=-1 WHERE callsign = '5*';
UPDATE channel SET xmltvid='spike.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Spike';
UPDATE channel SET xmltvid='moviemix.movies4men.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'Movie Mix';
UPDATE channel SET xmltvid='plus-1.london.itv1.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV +1';
UPDATE channel SET xmltvid='fv.plus-1.itv3.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'ITV3+1';
UPDATE channel SET xmltvid='quest.discoveryeurope.com', useonairguide=0, commmethod=-1 WHERE callsign = 'QUEST';
UPDATE channel SET xmltvid='plus-1.quest.discoveryeurope.com', useonairguide=0, commmethod=-1 WHERE callsign = 'QUEST+1';
UPDATE channel SET xmltvid='foodnetwork.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Food Network';
UPDATE channel SET xmltvid='plus-1.channel5.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Channel 5+1';
UPDATE channel SET xmltvid='challengetv.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'Challenge';
UPDATE channel SET xmltvid='4seven.channel4.com', useonairguide=0, commmethod=-1 WHERE callsign = '4seven';
UPDATE channel SET xmltvid='1.movies4men.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'movies4men';
UPDATE channel SET xmltvid='entertainment.truemovies.tv', useonairguide=0, commmethod=-1 WHERE callsign = 'True Entertainment';
UPDATE channel SET xmltvid='action.cbs.com', useonairguide=0, commmethod=-1 WHERE callsign = 'CBS Action';
UPDATE channel SET xmltvid='reality.cbs.com', useonairguide=0, commmethod=-1 WHERE callsign = 'CBS Reality';
UPDATE channel SET xmltvid='trutv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'truTV';
UPDATE channel SET xmltvid='drama.cbs.com', useonairguide=0, commmethod=-1 WHERE callsign = 'CBS Drama';
UPDATE channel SET xmltvid='cbbc.bbc.co.uk', useonairguide=0, commmethod=-2 WHERE callsign = 'CBBC';
UPDATE channel SET xmltvid='cbeebies.bbc.co.uk', useonairguide=0, commmethod=-2 WHERE callsign = 'CBeebies';
UPDATE channel SET xmltvid='citv.itv.com', useonairguide=0, commmethod=-1 WHERE callsign = 'CITV';
UPDATE channel SET xmltvid='popfun.co.uk', useonairguide=0, commmethod=-1 WHERE callsign = 'POP';
UPDATE channel SET xmltvid='tinypop.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Tiny Pop';
UPDATE channel SET xmltvid='news.bbc.co.uk', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC NEWS';
UPDATE channel SET xmltvid='parliament.bbc.co.uk', useonairguide=0, commmethod=-2 WHERE callsign = 'BBC Parliament';
UPDATE channel SET xmltvid='news.sky.com', useonairguide=0, commmethod=-1 WHERE callsign = 'Sky News';
